// Every country and language one could pick for a website, with its code
// (ISO 3166 for countries, ISO 639 for languages), in Dutch. Only offered
// as suggestions: one lands in the lists (Instellingen → Lijsten) once it's
// picked, so the lists keep only what's in use.

export type WorldEntry = { code: string; name: string };

const entries = (list: [string, string][]): WorldEntry[] => list.map(([code, name]) => ({ code, name }));

export const WORLD_COUNTRIES = entries([
  ["AF", "Afghanistan"],
  ["AX", "Ålandeilanden"],
  ["AL", "Albanië"],
  ["DZ", "Algerije"],
  ["AS", "Amerikaans-Samoa"],
  ["VI", "Amerikaanse Maagdeneilanden"],
  ["AD", "Andorra"],
  ["AO", "Angola"],
  ["AI", "Anguilla"],
  ["AQ", "Antarctica"],
  ["AG", "Antigua en Barbuda"],
  ["AR", "Argentinië"],
  ["AM", "Armenië"],
  ["AW", "Aruba"],
  ["AU", "Australië"],
  ["AZ", "Azerbeidzjan"],
  ["BS", "Bahama’s"],
  ["BH", "Bahrein"],
  ["BD", "Bangladesh"],
  ["BB", "Barbados"],
  ["BE", "België"],
  ["BZ", "Belize"],
  ["DY", "Benin"],
  ["BM", "Bermuda"],
  ["BT", "Bhutan"],
  ["BO", "Bolivia"],
  ["BQ", "Bonaire, Saba en Sint Eustatius"],
  ["BA", "Bosnië en Herzegovina"],
  ["BW", "Botswana"],
  ["BV", "Bouvet Island"],
  ["BR", "Brazilië"],
  ["IO", "Britse Gebieden in de Indische Oceaan"],
  ["VG", "Britse Maagdeneilanden"],
  ["BN", "Brunei"],
  ["BG", "Bulgarije"],
  ["HV", "Burkina Faso"],
  ["BI", "Burundi"],
  ["KH", "Cambodja"],
  ["CA", "Canada"],
  ["CF", "Centraal-Afrikaanse Republiek"],
  ["CL", "Chili"],
  ["CN", "China"],
  ["CX", "Christmaseiland"],
  ["CC", "Cocoseilanden"],
  ["CO", "Colombia"],
  ["KM", "Comoren"],
  ["CG", "Congo-Brazzaville"],
  ["ZR", "Congo-Kinshasa"],
  ["CK", "Cookeilanden"],
  ["CR", "Costa Rica"],
  ["CU", "Cuba"],
  ["CW", "Curaçao"],
  ["CY", "Cyprus"],
  ["DK", "Denemarken"],
  ["DJ", "Djibouti"],
  ["DM", "Dominica"],
  ["DO", "Dominicaanse Republiek"],
  ["DE", "Duitsland"],
  ["EC", "Ecuador"],
  ["EG", "Egypte"],
  ["SV", "El Salvador"],
  ["GQ", "Equatoriaal-Guinea"],
  ["ER", "Eritrea"],
  ["EE", "Estland"],
  ["SZ", "Eswatini"],
  ["ET", "Ethiopië"],
  ["FO", "Faeröer"],
  ["FK", "Falklandeilanden"],
  ["FJ", "Fiji"],
  ["PH", "Filipijnen"],
  ["FI", "Finland"],
  ["FX", "Frankrijk"],
  ["GF", "Frans-Guyana"],
  ["PF", "Frans-Polynesië"],
  ["TF", "Franse Gebieden in de zuidelijke Indische Oceaan"],
  ["GA", "Gabon"],
  ["GM", "Gambia"],
  ["GE", "Georgië"],
  ["GH", "Ghana"],
  ["GI", "Gibraltar"],
  ["GD", "Grenada"],
  ["GR", "Griekenland"],
  ["GL", "Groenland"],
  ["GP", "Guadeloupe"],
  ["GU", "Guam"],
  ["GT", "Guatemala"],
  ["GG", "Guernsey"],
  ["GN", "Guinea"],
  ["GW", "Guinee-Bissau"],
  ["GY", "Guyana"],
  ["HT", "Haïti"],
  ["HM", "Heard en McDonaldeilanden"],
  ["HN", "Honduras"],
  ["HU", "Hongarije"],
  ["HK", "Hongkong SAR van China"],
  ["IE", "Ierland"],
  ["IS", "IJsland"],
  ["IN", "India"],
  ["ID", "Indonesië"],
  ["IQ", "Irak"],
  ["IR", "Iran"],
  ["IM", "Isle of Man"],
  ["IL", "Israël"],
  ["IT", "Italië"],
  ["CI", "Ivoorkust"],
  ["JM", "Jamaica"],
  ["JP", "Japan"],
  ["YE", "Jemen"],
  ["JE", "Jersey"],
  ["JO", "Jordanië"],
  ["KY", "Kaaimaneilanden"],
  ["CV", "Kaapverdië"],
  ["CM", "Kameroen"],
  ["KZ", "Kazachstan"],
  ["KE", "Kenia"],
  ["KG", "Kirgizië"],
  ["KI", "Kiribati"],
  ["UM", "Kleine afgelegen eilanden van de Verenigde Staten"],
  ["KW", "Koeweit"],
  ["HR", "Kroatië"],
  ["LA", "Laos"],
  ["LS", "Lesotho"],
  ["LV", "Letland"],
  ["LB", "Libanon"],
  ["LR", "Liberia"],
  ["LY", "Libië"],
  ["LI", "Liechtenstein"],
  ["LT", "Litouwen"],
  ["LU", "Luxemburg"],
  ["MO", "Macao SAR van China"],
  ["MG", "Madagascar"],
  ["MW", "Malawi"],
  ["MV", "Maldiven"],
  ["MY", "Maleisië"],
  ["ML", "Mali"],
  ["MT", "Malta"],
  ["MA", "Marokko"],
  ["MH", "Marshalleilanden"],
  ["MQ", "Martinique"],
  ["MR", "Mauritanië"],
  ["MU", "Mauritius"],
  ["YT", "Mayotte"],
  ["MX", "Mexico"],
  ["FM", "Micronesia"],
  ["MD", "Moldavië"],
  ["MC", "Monaco"],
  ["MN", "Mongolië"],
  ["ME", "Montenegro"],
  ["MS", "Montserrat"],
  ["MZ", "Mozambique"],
  ["MM", "Myanmar (Birma)"],
  ["NA", "Namibië"],
  ["NR", "Nauru"],
  ["NL", "Nederland"],
  ["NP", "Nepal"],
  ["NI", "Nicaragua"],
  ["NC", "Nieuw-Caledonië"],
  ["NZ", "Nieuw-Zeeland"],
  ["NE", "Niger"],
  ["NG", "Nigeria"],
  ["NU", "Niue"],
  ["KP", "Noord-Korea"],
  ["MK", "Noord-Macedonië"],
  ["MP", "Noordelijke Marianen"],
  ["NO", "Noorwegen"],
  ["NF", "Norfolk"],
  ["UG", "Oeganda"],
  ["UA", "Oekraïne"],
  ["UZ", "Oezbekistan"],
  ["OM", "Oman"],
  ["TP", "Oost-Timor"],
  ["AT", "Oostenrijk"],
  ["PK", "Pakistan"],
  ["PW", "Palau"],
  ["PS", "Palestina"],
  ["PA", "Panama"],
  ["PG", "Papoea-Nieuw-Guinea"],
  ["PY", "Paraguay"],
  ["PE", "Peru"],
  ["PN", "Pitcairneilanden"],
  ["PL", "Polen"],
  ["PT", "Portugal"],
  ["PR", "Puerto Rico"],
  ["QA", "Qatar"],
  ["RE", "Réunion"],
  ["RO", "Roemenië"],
  ["SU", "Rusland"],
  ["RW", "Rwanda"],
  ["KN", "Saint Kitts en Nevis"],
  ["LC", "Saint Lucia"],
  ["VC", "Saint Vincent en de Grenadines"],
  ["BL", "Saint-Barthélemy"],
  ["MF", "Saint-Martin (Frans deel)"],
  ["PM", "Saint-Pierre en Miquelon"],
  ["SB", "Salomonseilanden"],
  ["WS", "Samoa"],
  ["SM", "San Marino"],
  ["ST", "São Tomé en Principe"],
  ["SA", "Saoedi-Arabië"],
  ["SN", "Senegal"],
  ["YU", "Servië"],
  ["SC", "Seychellen"],
  ["SL", "Sierra Leone"],
  ["SG", "Singapore"],
  ["SH", "Sint-Helena, Ascension en Tristan da Cunha"],
  ["SX", "Sint-Maarten (Nederlands deel)"],
  ["SI", "Slovenië"],
  ["SK", "Slowakije"],
  ["SD", "Soedan"],
  ["SO", "Somalië"],
  ["ES", "Spanje"],
  ["LK", "Sri Lanka"],
  ["SR", "Suriname"],
  ["SJ", "Svalbard en Jan Mayen"],
  ["SY", "Syrië"],
  ["TJ", "Tadzjikistan"],
  ["TW", "Taiwan"],
  ["TZ", "Tanzania"],
  ["TH", "Thailand"],
  ["TG", "Togo"],
  ["TK", "Tokelau"],
  ["TO", "Tonga"],
  ["TT", "Trinidad en Tobago"],
  ["TD", "Tsjaad"],
  ["CZ", "Tsjechië"],
  ["TN", "Tunesië"],
  ["TR", "Turkije"],
  ["TM", "Turkmenistan"],
  ["TC", "Turks- en Caicoseilanden"],
  ["TV", "Tuvalu"],
  ["UY", "Uruguay"],
  ["VU", "Vanuatu"],
  ["VA", "Vaticaanstad"],
  ["VE", "Venezuela"],
  ["UK", "Verenigd Koninkrijk"],
  ["AE", "Verenigde Arabische Emiraten"],
  ["US", "Verenigde Staten"],
  ["VN", "Vietnam"],
  ["WF", "Wallis en Futuna"],
  ["EH", "Westelijke Sahara"],
  ["BY", "Wit-Rusland"],
  ["ZM", "Zambia"],
  ["ZW", "Zimbabwe"],
  ["ZA", "Zuid-Afrika"],
  ["GS", "Zuid-Georgia en de Zuidelijke Sandwicheilanden"],
  ["KR", "Zuid-Korea"],
  ["SS", "Zuid-Soedan"],
  ["SE", "Zweden"],
  ["CH", "Zwitserland"],
]);

export const WORLD_LANGUAGES = entries([
  ["ab", "Abchazisch"],
  ["af", "Afrikaans"],
  ["sq", "Albanees"],
  ["am", "Amhaars"],
  ["ar", "Arabisch"],
  ["hy", "Armeens"],
  ["az", "Azerbeidzjaans"],
  ["eu", "Baskisch"],
  ["bn", "Bengaals"],
  ["my", "Birmaans"],
  ["bs", "Bosnisch"],
  ["br", "Bretons"],
  ["bg", "Bulgaars"],
  ["ca", "Catalaans"],
  ["zh", "Chinees"],
  ["co", "Corsicaans"],
  ["da", "Deens"],
  ["de", "Duits"],
  ["en", "Engels"],
  ["et", "Ests"],
  ["fi", "Fins"],
  ["fr", "Frans"],
  ["gl", "Galicisch"],
  ["ka", "Georgisch"],
  ["el", "Grieks"],
  ["ht", "Haïtiaans Creools"],
  ["iw", "Hebreeuws"],
  ["hi", "Hindi"],
  ["hu", "Hongaars"],
  ["ga", "Iers"],
  ["is", "IJslands"],
  ["in", "Indonesisch"],
  ["it", "Italiaans"],
  ["ja", "Japans"],
  ["kn", "Kannada"],
  ["kr", "Kanuri"],
  ["kk", "Kazachs"],
  ["km", "Khmer"],
  ["rw", "Kinyarwanda"],
  ["ko", "Koreaans"],
  ["hr", "Kroatisch"],
  ["lv", "Lets"],
  ["lt", "Litouws"],
  ["mk", "Macedonisch"],
  ["ml", "Malayalam"],
  ["ms", "Maleis"],
  ["mt", "Maltees"],
  ["mr", "Marathi"],
  ["mn", "Mongools"],
  ["nl", "Nederlands"],
  ["no", "Noors"],
  ["uk", "Oekraïens"],
  ["uz", "Oezbeeks"],
  ["om", "Oromo"],
  ["fa", "Perzisch"],
  ["pl", "Pools"],
  ["pt", "Portugees"],
  ["pa", "Punjabi"],
  ["ro", "Roemeens"],
  ["ru", "Russisch"],
  ["sg", "Sango"],
  ["sr", "Servisch"],
  ["si", "Singalees"],
  ["sl", "Sloveens"],
  ["sk", "Slowaaks"],
  ["es", "Spaans"],
  ["sw", "Swahili"],
  ["ta", "Tamil"],
  ["te", "Telugu"],
  ["th", "Thais"],
  ["bo", "Tibetaans"],
  ["cs", "Tsjechisch"],
  ["ce", "Tsjetsjeens"],
  ["tr", "Turks"],
  ["ur", "Urdu"],
  ["vi", "Vietnamees"],
  ["cy", "Welsh"],
  ["zu", "Zoeloe"],
  ["sv", "Zweeds"],
]);

// Suggestions for what's typed: names starting with it first, then the rest
// that contain it, leaving out the codes already in the list.
export function worldSuggestions(list: WorldEntry[], query: string, taken: string[], max = 6): WorldEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const have = new Set(taken.map((c) => c.toLowerCase()));
  const open = list.filter((e) => !have.has(e.code.toLowerCase()));
  const starts = open.filter((e) => e.name.toLowerCase().startsWith(q));
  const contains = open.filter((e) => !e.name.toLowerCase().startsWith(q) && e.name.toLowerCase().includes(q));
  return [...starts, ...contains].slice(0, max);
}

export const worldName = (list: WorldEntry[], code: string) =>
  list.find((e) => e.code.toLowerCase() === code.toLowerCase())?.name ?? null;
